# Make sure you are in scMEDAL_for_scRNAseq dir

import sys, os
os.chdir("/archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq")
sys.path.insert(0, os.getcwd())          # <-- add this right after the chdir

# The working dir should be scMEDAL_for_scRNAseq dir
print("working dir:",os.getcwd())


from models.models import train_model_on_named_experiment


# When you run your model, it outputs the figures, latent_space and saved_models directories, whitin those directories you will find a subdir with the name of the model trained, example: ASD/latent_space/scmedalfe/run_crossval_<run_name>
# Please copy the <run_name below> to analyze the results
# Update output paths of the models that you just run

from utils.defaults import ASD_OUTPUTS_DIR,ASD_EXPERIMENT_NAME
print(f"Loading outputs from {ASD_OUTPUTS_DIR}. Please verify that your models output folder is located here before proceeding with the analysis.")
import os
model_folder_dict = {
    "ae":"run_crossval_n_latent_dims-50_layer_units-512-132_use_batch_norm-True_scaling-min_max_model_type-ae_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_n_components-50_get_cf_batch-False_2025-07-10_03-10",
    "aec":"run_crossval_n_latent_dims-50_layer_units-512-132_n_pred-17_use_batch_norm-True_scaling-min_max_model_type-aec_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_get_cf_batch-False_2025-07-10_05-16",
    "scmedalfe":"run_crossval_loss_gen_weight-1_loss_recon_weight-1000_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfe_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-09_22-12",
    "scmedalfec":"run_crossval_loss_gen_weight-1_loss_recon_weight-2000_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfec_batch_size-512_epochs-500_patience-30_sample_size-10000_get_cf_batch-False_2025-07-10_00-42",
    "scmedalre":"run_crossval_loss_recon_weight-110_loss_latent_cluster_weight-0.1_n_latent_dims-50_layer_units-512-132_scaling-min_max_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-10_07-53",

    # To collect the comparable outputs (see below), you need to run the comparable models in /comparables. 

    "scVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_2025-07-16_23-16",
    "scANVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_2025-07-16_23-26",
    "scanorama":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-07-16_23-33",
    "harmony":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-07-16_23-39",
    "SAUCIE":"run_crossval_n_latent_dims-50_layers-512-132-50_lambda_b-0.0_lambda_c-0.0_lambda_d-0.0_learning_rate-0.0_scaling-min_max_batch_size-512_epochs-50_patience-30_sample_size-10000_model_type-ae_2025-07-17_00-36",
        }

model_paths = {k:os.path.join(ASD_OUTPUTS_DIR, "latent_space", ASD_EXPERIMENT_NAME,k, v) for k, v in model_folder_dict.items()}


## Run the Mixed Effects Classifier (MEC) on latent spaces generated by scmedalfe and scmedalre.
# classification targets: 3 patient groups (e.g., ASD vs. Normal)

n_pred = 2 #asd vs control
bio_col = "diagnosis"
# Run MEC  on latent spaces: scmedalfe
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True,
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":list(model_paths.keys()),
                                                   "latent_keys_config":{"fe_latent":"scmedalfe_latent"}})


# # Run MEC  on latent spaces: scmedalfe + scmedalre
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":list(model_paths.keys()),
                                                   "latent_keys_config":{"fe_latent":"scmedalfe_latent", "re_latent":"scmedalre_latent"}})


# Run MEC  on latent spaces:scmedalfec
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":list(model_paths.keys()),
                                                   "latent_keys_config":{"fe_latent":"scmedalfec_latent"}})


# Run MEC  on latent spaces: scmedalfec + scmedalre
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":list(model_paths.keys()),
                                                   "latent_keys_config":{"fe_latent":"scmedalfec_latent", "re_latent":"scmedalre_latent"}})


# Run MEC  on latent spaces: PCA
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":list(model_paths.keys()),
                                                   "get_pca":True, #necessary to calculate pca 
                                                   "latent_keys_config":{"fe_latent":"X_pca"}})


# Run MEC  on latent spaces: PCA+scmedalre
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["scmedalre"],
                                                   "get_pca":True, #necessary to calculate pca 
                                                   "latent_keys_config":{"fe_latent":"X_pca","re_latent":"scmedalre_latent"}})


# Run MEC  on latent spaces :scvi
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["scVI"],
                                                   "latent_keys_config":{"fe_latent":'scVI_latent'}})

# Run MEC  on latent spaces :scvi+scmedalre
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["scVI","scmedalre"],
                                                   "latent_keys_config":{"fe_latent":'scVI_latent', "re_latent":"scmedalre_latent"}})

# Run MEC on latent spaces :scANVI
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["scANVI"],
                                                   "latent_keys_config":{"fe_latent":'scANVI_latent'}})

# Run MEC on latent spaces :scANVI+"scmedalre"
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["scANVI","scmedalre"],
                                                   "latent_keys_config":{"fe_latent":'scANVI_latent',"re_latent":"scmedalre_latent"}})



# Run MEC on latent spaces :scanorama+scmedalre
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["scanorama"],
                                                   "latent_keys_config":{"fe_latent":'scanorama_latent'}})


# Run MEC  on latent spaces :scanorama
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["scanorama","scmedalre"],
                                                   "latent_keys_config":{"fe_latent":'scanorama_latent',"re_latent":"scmedalre_latent"}})

# Run MEC  on latent spaces :harmony
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["harmony"],
                                                   "latent_keys_config":{"fe_latent":'harmony_latent'}})

# Run MEC  on latent spaces :harmony +"scmedalre_latent"
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["harmony","scmedalre"],
                                                   "latent_keys_config":{"fe_latent":'harmony_latent',"re_latent":"scmedalre_latent"}})

# Run MEC on latent spaces :"SAUCIE"
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["SAUCIE"],
                                                   "latent_keys_config":{"fe_latent":"SAUCIE_latent"}})

# Run MEC  on latent spaces :"SAUCIE"+"scmedalre"
mec_aml = train_model_on_named_experiment("MEC", "ASD", 
                                    train_kwargs={#"quick":True, 
                                                    "results_path_dict":model_paths, },
                                    model_kwargs={"n_pred":n_pred,
                                                   "bio_col":bio_col,
                                                   "models_list":["SAUCIE","scmedalre"],
                                                   "latent_keys_config":{"fe_latent":"SAUCIE_latent","re_latent":"scmedalre_latent"}})





# Now get a summary table of all mec results
from utils.compare_results_utils import get_all_mec_metrics
df,_ = get_all_mec_metrics(ASD_OUTPUTS_DIR,ASD_EXPERIMENT_NAME, split='test')
print(df)